sudo: required
services:
  - docker
before_install:
  - docker pull yshalsager/cyanogenmod:latest
before_script:
- cd $HOME && mkdir twrp
- wget -q https://github.com/TwrpBuilder/twrp-sources/releases/download/omni_twrp-6.0.1-20180502/omni_twrp-6.0.1-20180502-norepo.tar.lzma
  -O $HOME/twrp.tar.lzma
- tar --lzma -xf twrp.tar.lzma --directory $HOME/twrp/ && rm twrp.tar.lzma
script:
  - cd $HOME/twrp/ && git clone https://github.com/zeorexdevs/android_device_ALLVIEW_gionee6735_65u_m0.git device/ALLVIEW/gionee6735_65u_m0
  - git clone https://github.com/zeorexdevs/device_generic_twrpbuilder.git device/generic/twrpbuilder
  - rm -rf bootable/recovery && git clone https://github.com/omnirom/android_bootable_recovery.git bootable/recovery
  - |
    docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/home/cmbuild/twrp/:rw,z" yshalsager/cyanogenmod bash << EOF
    cd /home/cmbuild/twrp/
    source build/envsetup.sh && lunch omni_gionee6735_65u_m0-eng && make -j16 recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/gionee6735_65u_m0/recovery.img $HOME/twrp/TWRP-$version-gionee6735_65u_m0-$(date +"%Y%m%d").img

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN_TB"
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: ZeoRexDevs/android_device_ALLVIEW_gionee6735_65u_m0
    branch: master

branches:
  except:
    - /^(?i:untagged)-.*$/
